-- Q1: The marketing team ran a campaign in june 2025 and wants to see how many new customers signed up during that period.
-- PARTY_ID - party
-- FIRST_NAME - person
-- LAST_NAME-person
-- EMAIL- contact_mech - INFO_STRING
-- PHONE - contact_mech - CONTACT_MECH_TYPE_ID - TELECOM_NUMBER
-- ENTRY_DATE - PARTY CREATED_DATE
--role ROLE_TYPE_ID
 -- WHERE CREATED_DATE, ROLE_TYPE_ID,

SELECT P.PARTY_ID, PER.FIRST_NAME, PER.LAST_NAME, P.CREATED_DATE,
(
  SELECT CM.INFO_STRING
  FROM CONTACT_MECH CM JOIN party_contact_mech PCM ON CM.CONTACT_MECH_ID = PCM.CONTACT_MECH_ID AND CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS'
  WHERE THRU_DATE IS NULL AND PCM.PARTY_ID = P.PARTY_ID
  LIMIT 1
) AS EMAIL,
(
  SELECT TN.CONTACT_NUMBER
  FROM TELECOM_NUMBER TN 
  JOIN PARTY_CONTACT_MECH CM 
  ON TN.CONTACT_MECH_ID = CM.CONTACT_MECH_ID 
  WHERE THRU_DATE IS NULL AND CM.PARTY_ID = P.PARTY_ID
  LIMIT 1
) AS PHONE
FROM PARTY P
JOIN PERSON PER ON P.PARTY_ID = PER.PARTY_ID 
JOIN PARTY_ROLE PR ON P.PARTY_ID = PR.PARTY_ID AND PR.ROLE_TYPE_ID = 'CUSTOMER' -- SINGLE CUSTOMER
WHERE P.CREATED_DATE >= '2025-06-01' AND P.CREATED_DATE <= '2025-06-30'

--Q2: List All Active Physical Products
Business Problem:
Merchandising teams often need a list of all physical products to manage logistics, warehousing, and shipping.

Fields to Retrieve:

PRODUCT_ID
PRODUCT_TYPE_ID
INTERNAL_NAME

SELECT 
  P.PRODUCT_ID, 
  P.INTERNAL_NAME, 
  PT.PRODUCT_TYPE_ID 
FROM 
  PRODUCT P 
  JOIN PRODUCT_TYPE PT ON P.PRODUCT_TYPE_ID = PT.PRODUCT_TYPE_ID 
WHERE 
  IS_PHYSICAL = 'Y' 
  AND SALES_DISCONTINUATION_DATE IS NULL 
  OR SALES_DISCONTINUATION_DATE >= NOW()
